### ISSUE TITLE
Be more subtle when line edition is not available.

### ISSUE THREAD

**Issue by ivg** [dbuenzli/down#17]
Here is a simple repro

```
        OCaml version 4.07.0

# #use "down.top";;
Warning: Down v0.0.1 disabled. No ANSI terminal capability detected.
# Down.Session.record ();;
- : unit = ()
# print_endline "hello, world";;
hello, world
- : unit = ()
# Down.Session.save "hello_world";;
Exception: Failure "tl".
# 
```

I'm not sure whether it is a bug or a limitation of Emacs.

**Comment by dbuenzli** [comment]
Ah yes sorry in fact [my comment](https://discuss.ocaml.org/t/ann-down-0-0-1/4140/11?u=dbuenzli) was about using sessions, not recording them. That won't work I need to see the phrases that get in and thus have the OCaml readline patching installed.

But apparently the recording functions assumes the readline patching is in place. It should error more gracefully if it's not.

**Comment by dbuenzli** [comment]
Thanks for the report.
