### ISSUE TITLE
Crash after trying to get type of empty (non-inputed) identifier

### ISSUE THREAD

**Issue by Kakadu** [dbuenzli/down#23]
To crash you need to load Down.0.0.2 and press Ctrl-T without pressing any other keys

```
# #use "down.top";;
Down v0.0.2 loaded. Type Down.help () for more info.
# Fatal error: exception Invalid_argument("index out of bounds")

```

**Comment by dbuenzli** [comment]
Thanks for the report !

**Comment by Fourchaux** [comment]
Sorry to re-open this, but I still have the same problem.

Config: OCaml 4.10.0+flambda - Down v0.0.2 (opam version) - Linux box x86_64.

**Comment by dbuenzli** [comment]
Mmmh it seems we need a release ! Can you please confirm `opam pin down --dev` works ?

**Comment by Fourchaux** [comment]
Yep, ```opam pin``` works.

**Comment by dbuenzli** [comment]
Thanks ! Will try to do a release over the weekend.
