### ISSUE TITLE
down only recognizes the first top-level statement of several ones when copy-and-pasted

### ISSUE THREAD

**Issue by aqjune** [dbuenzli/down#30]
Hi, thanks for a nice tool.

I found that down only recognizes the first statement when I copy-and-pasted several statements at once.

For example, let's assume that I copied these two lines from somewhere:
```
let x = 10;;
let y = 20;;
```

If I paste it at ocaml after `#use "down.top"`, only `x` is defined, but not `y`.

```
OCaml version 4.14.0
Enter #help;; for help.

# #use "down.top";;
Down v0.1.0 loaded. Type Down.help () for more info.
# let x = 10;;
val x : int = 10
# (* where is y? *)
```

Thanks!

**Comment by dbuenzli** [comment]
Yes that's a limitation of `ocaml` itself see https://github.com/ocaml/ocaml/issues/8813

**Comment by aqjune** [comment]
Oh, I didn't realize that was the limitation of `ocaml` itself. I wasn't aware of it because I was using `rlwrap ocaml` which successfully deals with this case. I will leave a comment there.

**Comment by dbuenzli** [comment]
> `rlwrap ocaml` which successfully deals with this case.

Mmmh I guess it splits on newlines and feeds it line by line. But something like pasting 
`let x = 10;; let y = 20;;` shouldn't work.

**Comment by aqjune** [comment]
I see, so even `rlwrap` isn't the complete solution yet. Will close this issue since this is `ocaml`'s problem
