### ISSUE TITLE
Completion does not take opens into account

### ISSUE THREAD

**Issue by kit-ty-kate** [dbuenzli/down#31]
```
# #require "containers";;
# open Containers;;
# List.<tab>
```
the completion here only shows `Stdlib.List`, not the expected `Containers.List`.

I’m not sure if this is an issue in `down` or in `ocp-index`. If it is the latter could you give the rough command used so that I can report the issue properly?

**Comment by dbuenzli** [comment]
Indeed. That's tracked in #11.
