### ISSUE TITLE
Support `NO_COLOR`

### ISSUE THREAD

**Issue by henrytill** [dbuenzli/down#32]
Hi, thanks for the great tool.

Would you be open to adding support for the [`NO_COLOR`](https://no-color.org/) environment variable?  

I sketched out a very basic approach [here](https://github.com/dbuenzli/down/compare/master...henrytill:down:no-color).

**Comment by dbuenzli** [comment]
If anything I'm rather sympathetic to add support for `OCAML_COLOR` and/or `TERM=dumb`. I think `NO_COLOR` is a bad standard, someone explained it better than me [there](https://news.ycombinator.com/item?id=17244313).

**Comment by henrytill** [comment]
Okay, understood.

**Comment by dbuenzli** [comment]
> and/or `TERM=dumb`.

Well if `TERM=dumb` you can't really provide the service. But obeying  `OCAML_COLOR` seems appropriate.
