### ISSUE TITLE
A failure due to missing file permission in `~/.config/ocaml/session`

### ISSUE THREAD

**Issue by aqjune** [dbuenzli/down#36]
I might be missing something, but in WSL2 Ubuntu, `Down.Session.edit` is failing because `~/.config/ocaml/session/` does not have `+x` permission:
```
$ cd ~
$ ls -al
drw-r--r--  2 aqjune aqjune 4.0K May  4 00:15 .config
```
To make `Down.Session.edit` successful, `chmod +x` must be given to all three directories `.config`,`.config/ocaml`,`.config/ocaml/session/`.
```
# Down.Session.edit "mysession";;
Error: /home/aqjune/.config/ocaml: Permission denied
Error: /home/aqjune/.config/ocaml: Permission denied
val it : unit = ()
# Down.Session.edit "mysession";;
Error: /home/aqjune/.config/ocaml/session: Permission denied
Error: /home/aqjune/.config/ocaml/session: Permission denied
val it : unit = ()
# Down.Session.edit "mysession";;
Error: /home/aqjune/.config/ocaml/session/last: Permission denied
Error: /home/aqjune/.config/ocaml/session/mysession.ml: Permission denied
val it : unit = ()
```

**Comment by nojb** [comment]
Oops, I think this is my fault:

https://github.com/dbuenzli/down/blob/5b557f38226974ca6e98827dc61e9e5ee57464a7/src/down_std.ml#L287

should be `0o755`.

Apologies.

**Comment by dbuenzli** [comment]
No worries a good reviewer would have spotted that :-). On a fix.

**Comment by aqjune** [comment]
thanks! :)

**Comment by MisterDA** [comment]
I also got this error on `~/.config/ocaml/history.ml` and had to `chmod +x ~/.config/ocaml`, using Down 0.4.0 and OCaml 4.14. Btw, the history should probably be stored in `$XDG_STATE_HOME` instead of the config directory.

**Comment by dbuenzli** [comment]
But was your `~/.config/ocaml` *created* by Down 0.4.0 ? This should be fixed.

**Comment by MisterDA** [comment]
> But was your `~/.config/ocaml` _created_ by Down 0.4.0 ? This should be fixed.

I can't guarantee it, but there was nothing inside of the directory, so it's quite possible.
