### ISSUE TITLE
mark and kill region

### ISSUE THREAD

**Issue by hannesm** [dbuenzli/down#5]
Hello Daniel,

thanks for sharing your code. I run into trouble (all US-ASCII characters) when I mark at some position, then move one character left or right and kill-region. My expectation is that the single character I marked will be killed (this is the behaviour of emacs). The behaviour of `down` is to kill two characters. Is this intentional?

**Comment by dbuenzli** [comment]
No. Thanks for the report !

**Comment by hannesm** [comment]
Thanks for your prompt fix!
